import { StyleSheet } from 'react-native';
import { colors, spacing, radius } from '../../theme';

export const detailStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: { padding: spacing.lg, paddingBottom: spacing.xxl },
  statusRow: { alignItems: 'center', marginBottom: spacing.md },
  badge: { backgroundColor: '#FFF', borderWidth: 1, borderColor: '#E8E4DE', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 6 },
  badgePublished: { backgroundColor: '#E8F8ED', borderColor: '#E8F8ED' },
  badgeText: { fontSize: 13, fontWeight: '600', color: colors.textSecondary },
  badgeTextPublished: { color: colors.success },
  card: { backgroundColor: '#FFF', borderRadius: radius.xl, padding: spacing.xl, alignItems: 'center', elevation: 4, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 16, marginBottom: spacing.lg },
  cardLabel: { fontSize: 11, textTransform: 'uppercase', letterSpacing: 1.5, color: colors.textMuted, marginBottom: spacing.md },
  coupleNames: { fontSize: 26, fontWeight: '300', color: colors.textPrimary, textAlign: 'center' },
  divider: { width: 50, height: 1.5, backgroundColor: colors.gold, marginVertical: spacing.md },
  cardTitle: { fontSize: 14, color: colors.textMuted, fontStyle: 'italic', marginBottom: spacing.md },
  detailText: { fontSize: 14, color: colors.textSecondary, marginBottom: spacing.xs },
  shareBox: { backgroundColor: '#FFF', borderRadius: radius.lg, padding: spacing.lg, alignItems: 'center', gap: spacing.md, borderWidth: 1, borderColor: '#D4EDDA', marginBottom: spacing.lg },
  shareIcon: { fontSize: 32 },
  shareLabel: { fontSize: 17, fontWeight: '700', color: colors.success },
  urlInput: { width: '100%', backgroundColor: '#F8F8F8', borderWidth: 1, borderColor: '#E8E4DE', borderRadius: radius.sm, paddingHorizontal: 12, paddingVertical: 12, fontSize: 12, textAlign: 'center' },
  shareActions: { flexDirection: 'row', gap: 10 },
  copyBtn: { backgroundColor: '#F0EBE3', borderRadius: 10, paddingHorizontal: 18, paddingVertical: 10 },
  copyBtnText: { fontSize: 13, fontWeight: '600', color: colors.textPrimary },
  shareBtn: { backgroundColor: colors.gold, borderRadius: 10, paddingHorizontal: 18, paddingVertical: 10 },
  shareBtnText: { fontSize: 13, fontWeight: '600', color: '#FFF' },
  publishBtn: { backgroundColor: colors.gold, borderRadius: radius.lg, paddingVertical: spacing.md, alignItems: 'center', marginBottom: spacing.lg, shadowColor: colors.gold, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 4 },
  publishBtnDisabled: { opacity: 0.6 },
  publishBtnText: { color: '#FFF', fontSize: 16, fontWeight: '700' },
  rsvpSection: { backgroundColor: '#FFF', borderRadius: radius.lg, padding: spacing.lg },
  rsvpHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.md },
  rsvpTitle: { fontSize: 16, fontWeight: '700', color: colors.textPrimary },
  rsvpStats: { fontSize: 13, fontWeight: '600', color: colors.textMuted },
  rsvpRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#F5F3F0', gap: spacing.md },
  rsvpAvatar: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#F0EBE3', justifyContent: 'center', alignItems: 'center' },
  rsvpAvatarText: { fontSize: 14, fontWeight: '700', color: colors.gold },
  rsvpInfo: { flex: 1 },
  rsvpName: { fontSize: 14, fontWeight: '600', color: colors.textPrimary },
  rsvpMeta: { fontSize: 12, color: colors.textMuted, marginTop: 1 },
  rsvpBadge: { borderRadius: 12, paddingHorizontal: 10, paddingVertical: 4 },
  rsvpGreen: { backgroundColor: '#E8F8ED' },
  rsvpRed: { backgroundColor: '#FDE8E8' },
  rsvpBadgeText: { fontSize: 12, fontWeight: '700' },
  rsvpGreenText: { color: colors.success },
  rsvpRedText: { color: colors.danger },
});
