import { StyleSheet } from 'react-native';
import { colors, spacing, radius } from '../../theme';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  scrollContainer: { flex: 1, backgroundColor: colors.background },
  scrollContent: { padding: spacing.lg, paddingBottom: spacing.xxl },
  templateBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#F0EBE3',
    borderRadius: radius.lg,
    padding: 14,
    marginBottom: spacing.xl,
  },
  thumb: { width: 52, height: 52, borderRadius: radius.sm, backgroundColor: '#F0EBE3' },
  thumbFallback: { width: 52, height: 52, borderRadius: radius.sm, backgroundColor: '#F0EBE3', justifyContent: 'center', alignItems: 'center' },
  thumbIcon: { fontSize: 22 },
  templateInfo: { flex: 1 },
  templateLabel: { fontSize: 11, color: colors.textMuted, fontWeight: '500' },
  templateName: { fontSize: 15, fontWeight: '700', color: colors.textPrimary, marginTop: 2 },
  changeBtn: { paddingHorizontal: spacing.md, paddingVertical: spacing.xs + 2, borderRadius: radius.sm, backgroundColor: '#F5F3F0' },
  changeBtnText: { fontSize: 12, fontWeight: '600', color: colors.textSecondary },
  heading: { fontSize: 24, fontWeight: '800', color: colors.textPrimary, letterSpacing: -0.3 },
  subtitle: { fontSize: 14, color: colors.textSecondary, marginTop: 6, marginBottom: spacing.lg, lineHeight: 20 },
  form: { gap: 14 },
  sectionText: { fontSize: 13, fontWeight: '600', color: colors.textSecondary, marginTop: spacing.sm },
  row: { flexDirection: 'row', gap: spacing.md },
  submitBtn: {
    backgroundColor: colors.gold,
    borderRadius: radius.lg,
    paddingVertical: spacing.md,
    alignItems: 'center',
    marginTop: spacing.xl,
    shadowColor: colors.gold,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  submitBtnDisabled: { opacity: 0.6 },
  submitBtnText: { color: '#FFF', fontSize: 16, fontWeight: '700' },
});
