import { StyleSheet } from 'react-native';
import { colors, spacing, radius } from '../../theme';

export const publicStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FAF8F5' },
  content: { paddingTop: 60, paddingHorizontal: spacing.lg, paddingBottom: spacing.xxl },
  card: { backgroundColor: '#FFF', borderRadius: radius.xl + 4, padding: 40, alignItems: 'center', elevation: 4, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 20, marginBottom: spacing.lg },
  floral: { color: colors.gold, fontSize: 16, letterSpacing: 8, marginVertical: spacing.sm },
  label: { fontSize: 11, textTransform: 'uppercase', letterSpacing: 2, color: colors.textMuted, marginBottom: spacing.md },
  couple: { fontSize: 28, fontWeight: '300', color: colors.textPrimary, textAlign: 'center', lineHeight: 38 },
  amp: { fontSize: 22, fontStyle: 'italic', color: colors.gold },
  title: { fontSize: 13, color: colors.textMuted, fontStyle: 'italic', marginTop: spacing.md },
  divider: { width: 50, height: 1.5, backgroundColor: colors.gold, marginVertical: spacing.md },
  date: { fontSize: 15, fontWeight: '600', color: colors.textPrimary },
  time: { fontSize: 14, color: colors.textSecondary, marginTop: spacing.xs },
  venue: { fontSize: 14, color: colors.textSecondary, marginTop: spacing.sm, textAlign: 'center' },
  success: { backgroundColor: '#FFF', borderWidth: 1.5, borderColor: '#D4EDDA', borderRadius: radius.xl, padding: spacing.xl, alignItems: 'center', marginBottom: spacing.lg },
  successIcon: { fontSize: 40, marginBottom: spacing.sm },
  successTitle: { fontSize: 20, fontWeight: '800', color: colors.success },
  successMsg: { fontSize: 14, color: colors.textSecondary, marginTop: spacing.sm },
  rsvpForm: { backgroundColor: '#FFF', borderRadius: radius.xl, padding: spacing.lg, marginBottom: spacing.lg, elevation: 2 },
  rsvpTitle: { fontSize: 20, fontWeight: '800', color: colors.textPrimary, marginBottom: spacing.xs },
  rsvpSub: { fontSize: 14, color: colors.textMuted, marginBottom: spacing.lg },
  input: { backgroundColor: '#F8F8F8', borderWidth: 1.5, borderColor: '#E8E4DE', borderRadius: radius.md, paddingHorizontal: 14, paddingVertical: 13, fontSize: 15, color: colors.textPrimary, marginBottom: spacing.md },
  toggleRow: { flexDirection: 'row', gap: 10, marginBottom: spacing.md },
  toggle: { flex: 1, borderWidth: 1.5, borderColor: '#E8E4DE', borderRadius: radius.md, paddingVertical: 14, alignItems: 'center' },
  toggleYes: { backgroundColor: '#E8F8ED', borderColor: colors.success },
  toggleNo: { backgroundColor: '#FDE8E8', borderColor: colors.danger },
  toggleText: { fontSize: 14, fontWeight: '600', color: colors.textSecondary },
  toggleYesText: { color: colors.success },
  toggleNoText: { color: colors.danger },
  submitBtn: { backgroundColor: colors.gold, borderRadius: radius.lg, paddingVertical: 15, alignItems: 'center', marginTop: spacing.sm },
  submitDisabled: { opacity: 0.6 },
  submitText: { color: '#FFF', fontSize: 15, fontWeight: '700' },
  footer: { textAlign: 'center', fontSize: 12, color: colors.textMuted, marginTop: spacing.md },
});
